# Generated by Django 4.1.4 on 2023-03-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resizeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('flipRight', models.IntegerField(default=0)),
                ('flipLeft', models.IntegerField(default=0)),
                ('flipTop', models.IntegerField(default=0)),
                ('flipDown', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
